# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bad5eebe63259f739169f2c09fa40537b0020d46add25fd8655684b0797c1026ff34d5355112a6ebc87bc6264a2827eeefa8d3761f846ac58db9aeac589162a4

test:
  secret_key_base: a797412a8914b244266cd3c8f28cc82233a928f58db8ae24364725ef22bbb8d06eb44ba6b54318b2db56cbbf76780910990175341a09537c4e3ed33199b51a8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
